server {
    listen 80;
    server_name localhost;

    # 前端静态文件配置
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri /index.html; # 解决 React 路由刷新 404
    }

    # 后端 API 代理配置（统一接口路径）
    location /api/ {
        proxy_pass http://user-center-backend:8080/; # 注意：这里使用容器服务名 backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
